#ifndef _DRIVERS_KEYBOARD_ASCII_H
#define _DRIVERS_KEYBOARD_ASCII_H

#define ASCII_NONE                (0x00)
#define ASCII_ENTER               ('\n')
#define ASCII_TAB                 ('\t')
#define ASCII_ESC                 (0x1B)
#define ASCII_BACKSPACE           (0x08)
#define ASCII_CTRL                (0x81)
#define ASCII_LSHIFT              (0x82)
#define ASCII_RSHIFT              (0x83)
#define ASCII_PRINTSCREEN         (0x84)
#define ASCII_LALT                (0x85)
#define ASCII_CAPSLOCK            (0x86)
#define ASCII_F1                  (0x87)
#define ASCII_F2                  (0x88)
#define ASCII_F3                  (0x89)
#define ASCII_F4                  (0x8A)
#define ASCII_F5                  (0x8B)
#define ASCII_F6                  (0x8C)
#define ASCII_F7                  (0x8D)
#define ASCII_F8                  (0x8E)
#define ASCII_F9                  (0x8F)
#define ASCII_F10                 (0x90)
#define ASCII_NUMLOCK             (0x91)
#define ASCII_SCROLLLOCK          (0x92)
#define ASCII_HOME                (0x93)
#define ASCII_UP                  (0x94)
#define ASCII_PAGEUP              (0x95)
#define ASCII_LEFT                (0x96)
#define ASCII_CENTER              (0x97)
#define ASCII_RIGHT               (0x98)
#define ASCII_END                 (0x99)
#define ASCII_DOWN                (0x9A)
#define ASCII_PAGEDOWN            (0x9B)
#define ASCII_INS                 (0x9C)
#define ASCII_DEL                 (0x9D)
#define ASCII_F11                 (0x9E)
#define ASCII_F12                 (0x9F)
#define ASCII_PAUSE               (0xA0)

#endif
